[package]
name = "rust-compressor"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "Rust implementation of RLE and LZ77 compression algorithms"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0" 