name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Rust compressor
        uses: docker/build-push-action@v5
        with:
          context: ./rust-compressor
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/rust-compressor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push JS compressor
        uses: docker/build-push-action@v5
        with:
          context: ./js-compressor
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/js-compressor:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
